[phases.setup]
nixPkgs = ['nodejs', 'npm']

[phases.install]
cmds = ['cd server && npm ci']

[phases.build]
cmds = ['echo "No build step needed for Node.js server"']

[start]
cmd = 'cd server && npm start'