name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - 'server/**'
      - 'server.js'
      - 'package.json'
      - 'vercel.json'
  workflow_dispatch: {}

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Test server startup
        run: |
          echo "Testing server can start..."
          # Create a test .env file
          mkdir -p server
          echo "OPENAI_API_KEY=test-key" > server/.env
          timeout 5s node server.js || echo "Server startup test completed"
        env:
          NODE_ENV: test

  deploy-vercel:
    needs: test-backend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./